version: '3'
services:
  auth-api:
    build: './auth-api'
    container_name: nodejs-auth-api
    ports:
      - "8080:8080"
    depends_on: 
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

volumes:
  db-data: